version: 2.1

orbs:
  onegini-build: onegini/onegini-build@3

.dev-context-and-executor: &dev-context-and-executor
  context: dev-context
  executor:
    name: onegini-build/maven-builder
    tag: "11.0"

.component-type-application: &component-type-application
  component_type: application

.require-build: &require-build
  requires:
    - build

.filter-tags-only: &filter-tags-only
  filters:
    tags:
      only: /.*/
    branches:
      ignore: /.*/

workflows:
  version: 2
  security-proxy-request-mapper-workflow:
    jobs:
      - onegini-build/build-install:
          name: build
          <<: *dev-context-and-executor
          <<: *component-type-application

      - onegini-build/maven:
          name: docker-snapshot
          <<: *dev-context-and-executor
          <<: *component-type-application
          <<: *require-build
          goal: pl.project13.maven:git-commit-id-plugin:revision jib:build
          profiles: jib

      - onegini-build/docker-release-promote:
          name: docker-release
          <<: *dev-context-and-executor
          <<: *filter-tags-only

      - onegini-build/notify-released:
          name: norify-released
          context: dev-context
          <<: *filter-tags-only
          requires:
            - docker-release
